trigger: none
pr: none

parameters:
  - name: environment
    type: string
    default: demo
  - name: location
    type: string
    default: brazilsouth
  - name: prefix
    type: string
    default: tc4fb
  - name: action
    type: string
    default: deploy
    values:
      - deploy
      - destroy

pool:
  vmImage: ubuntu-latest

variables:
  rgName: rg-$(prefix)-$(environment)

steps:
  - task: AzureCLI@2
    displayName: Azure login + infra $(action)
    inputs:
      azureSubscription: $(AZURE_SERVICE_CONNECTION)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        echo "Resource group: $(rgName)"
        if [ "${{ parameters.action }}" = "destroy" ]; then
          az group delete --name "$(rgName)" --yes --no-wait
          exit 0
        fi

        az group create --name "$(rgName)" --location "${{ parameters.location }}"

        az deployment group create \
          --resource-group "$(rgName)" \
          --name "deploy-$(Build.BuildId)" \
          --template-file infra/main.bicep \
          --parameters \
            prefix="${{ parameters.prefix }}" \
            location="${{ parameters.location }}" \
            criticalQueueName="critical-feedback" \
            cosmosDatabaseName="feedbackdb" \
            cosmosContainerName="feedbacks" \
            emailFrom="$(EMAIL_FROM)" \
            adminEmailTo="$(ADMIN_EMAIL_TO)" \
            acsEmailConnectionString="$(ACS_EMAIL_CONNECTION_STRING)"

