quarkus.azure-functions.app-name=${AZURE_FUNCTIONAPP_NAME:tc4fb-func}
quarkus.azure-functions.runtime.java-version=21
quarkus.http.root-path=/api

# Logs (úteis para visualizar no Application Insights / Log stream)
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b %D
quarkus.log.level=INFO
